### PR TITLE
Add button to share your score on Twitter

### PR DESCRIPTION
**Pull request by bennetthanna**
References #18

### CODE REVIEW

**Comment by itaditya** [comment]
@bennetthanna I have added a comment here https://github.com/itaditya/trick-or-treat-game/issues/18#issuecomment-538078140. Please read it and update accordingly.

**Comment by bennetthanna** [comment]
image

image

@itaditya Here's what the end product looks like. Let me know what you think! I'm open to any and all recommendations 🙂

**Comment by itaditya** [comment]
This looks great. Can you make one change though. Instead of hardcoding the netlify link, use the `window.location.origin` to get the location of website and then use that inside the share widget.

**Comment by itaditya** [comment]
@bennetthanna congrats on getting your PR merged! Happy Hacktoberfest

Congrats

**Pull request merged**
