### PR TITLE
Add twitter share button

### PR DESCRIPTION
**Pull request by kaikecarlos**

### CODE REVIEW

**Comment by kaikecarlos** [comment]
don't merge, for some reason `react-twitter-embed` is giving some error(related to babel)

**Comment by itaditya** [comment]
As discussed here, we don't need a full library for this https://github.com/itaditya/trick-or-treat-game/issues/18#issuecomment-536903130

**Comment by kaikecarlos** [comment]
oh, I will fix ASAP

**Comment by itaditya** [comment]
Hi @kaikecarlos thanks for working on this feature. However has almost completed the feature [here](https://github.com/itaditya/trick-or-treat-game/pull/45) and that's why I have assigned that issue to her. But there are lot more issues open. You can pick those up. Another thing you can do is play the game and find issues and then if they seem valid I'll assign those to you.

**Comment by itaditya** [comment]
@bennetthanna PR has been merged

**Pull request closed without merging**
